# Generated by Django 2.0.6 on 2018-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpUser',
            fields=[
                ('user_id', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=30, null=True)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('username', models.CharField(db_column='UserName', max_length=20)),
            ],
            options={
                'db_table': 'signup',
                'managed': True,
            },
        ),
    ]
