# Generated by Django 2.0.6 on 2018-07-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0002_signupuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'managed': False},
        ),
    ]
