# Generated by Django 2.0.6 on 2018-07-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0003_auto_20180727_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpUser',
        ),
    ]
